### ISSUE TITLE
when click setting, found 404!

### ISSUE THREAD

**Issue by gisok** [Yarroo/redmine-plugin-send_notification#1]
Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.4.2-p198 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  nxs_chat                       2.0
  redmine_issue_todo_lists       1.1.2
  redmine_knowledgebase          3.2.1
  send_notification              0.0.2

**Comment by Yarroo** [comment]
Sorry for waiting, I'm new to github, just noticed issue. I'll try to fix it as soon as possible.

**Comment by ohmkit** [comment]
I have same issue.

Environment:
  Redmine version                3.4.4.stable
  Ruby version                   2.3.6-p384 (2017-12-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.7
  Cvs                            1.12.13
  Git                            2.14.1
  Filesystem                     
Redmine plugins:
  send_notification              0.0.3

**Comment by Yarroo** [comment]
Add erb template for settings, must work. Please update plugin. Please let me know if the error disappears
